### ISSUE TITLE
Chat support?

### ISSUE THREAD

**Issue by kinsi55** [SzymonLisowiec/node-epicgames-client#1]
Any chance you've looked into chat support before?

**Comment by SzymonLisowiec** [comment]
I'm going to take care of chat and realtime notifications (e.g. invite to friends), but I don't have many free time now. Thanks for tips. We can connect to *hidden* and listen to data, but I'm not sure, if we need send something like an authorization header.

**Comment by mitchellcarter** [comment]
@kinsi55 - I see you've made some progress on the social/chat client. Would you mind contributing some of the code to the repo, or a perhaps making your own package?

**Comment by kinsi55** [comment]
@mcarter4 Unfortunately I am not interested in publicly spreading on how this works. The community of the game we play is undoubtfully super young, and there already is bots going around who spam-add people at random with scam links as their username, but if it was possible for them to actually make their bot chat incase the friend request is accepted the situation certainly wouldnt get any better, and I'd rather not like for this to get cut down / blocked for my use-case just because of pieces of shit. It'll probably eventually be found by somebody else than me but I'd rather have that happen later than sooner.

**Comment by mitchellcarter** [comment]
I get it. It really only delayed my work by an hour or two. It only took Wireshark and some spec references to figure it out. Thanks anyways.

**Comment by Hundeklemmen** [comment]
@mcarter4 WIll it be possible to get a copy of the chatsystem you made? (Private)

**Comment by kinsi55** [comment]
@Hundeklemmen If you really need it look into it yourself. Who's gonna gurantee that you wont abuse it / keep it private to yourself.

**Comment by SzymonLisowiec** [comment]
Added in version 1.0 (https://github.com/SzymonLisowiec/node-epicgames-client/commit/7bfb5410919035f915d17720c474de883b45fb3b)
