### ISSUE TITLE
Add Client.getDisplayName() Method

### ISSUE THREAD

**Issue by ShadowRanger** [SzymonLisowiec/node-epicgames-client#12]
A method to return the client's display name, and also potentially their account ID if possible would be helpful.

**Comment by ShadowRanger** [comment]
Nevermind, I can see that this is already possible with client.account.display_name.

**Comment by SzymonLisowiec** [comment]
I have improved access to client properties and descriped in [README](https://github.com/SzymonLisowiec/node-epicgames-client#properties).

**Comment by ShadowRanger** [comment]
Thank you for that @SzymonLisowiec
