### ISSUE TITLE
Client Auth Access Error

### ISSUE THREAD

**Issue by ShadowRanger** [SzymonLisowiec/node-epicgames-client#15]
When initializing a client,  I am getting this error:
`Error: errors.com.epicgames.common.oauth.unauthorized_client`

**Comment by SzymonLisowiec** [comment]
All informations about that issue you can find here: https://github.com/qlaffont/fortnite-api/issues/152

**Comment by ShadowRanger** [comment]
Thank you

**Comment by Velkon** [comment]
Epic games blocked the password token_type in oauth, I've hackily fixed this myself by going through the actual auth process that the launcher goes through and using the exchange_code it returns through oauth. That seems to be the only way to do it at the moment. (It also allows support for 2fa)

**Comment by ShadowRanger** [comment]
> Epic games blocked the password token_type in oauth, I've hackily fixed this myself by going through the actual auth process that the launcher goes through and using the exchange_code it returns through oauth. That seems to be the only way to do it at the moment. (It also allows support for 2fa)

Are you referring to the access_token that is returned with **/account/api/oauth/token**? I am having trouble seeing where this **access_token** is used to fully authenticate the user after the initial OAuth connection with **client_credentials**.

**Comment by Velkon** [comment]
@ShadowRanger This is how I'm doing it (Since Epic blocked the password token_type in OAuth, you now need to get an exchange_code)
```
I'm not really a web dev, so there might be a less hacky way of doing it. 

Firstly, you need to get a XSRF-TOKEN cookie from sending a GET request to 
"https://accounts.launcher-website-prod07.ol.epicgames.com/login/doLauncherLogin?client_id=" + clientID + "&redirectUrl=https%3A%2F%2Faccounts.launcher-website-prod07.ol.epicgames.com%2Flogin%2FshowPleaseWait%3Fclient_id%3D" + clientID + "%26rememberEmail%3Dfalse"

and the XSRF-TOKEN cookie should be in the response headers. (It has an empty body iirc)

Send a post request to https://accounts.launcher-website-prod07.ol.epicgames.com/login/doLauncherLogin with params:

fromForm: "yes",
authType: null,
linkExtAuth: null,
client_id: clientId,
redirectUrl: "https://accounts.launcher-website-prod07.ol.epicgames.com/login/showPleaseWait?client_id=" + clientId + "&rememberEmail=false",
epic_username: email,
password: password,
rememberMe: "NO" // w/e you want between "NO" and "YES"

If login is ok it will return a JSON with redirectURL. (The same one you sent)

http Fetch the redirectURL:

Once the redirectURL is returned, 
the only way I found to get the exchange_code is to string match for  
com.epicgames.account.web.widgets.loginWithExchangeCode
(Since it's a html page)


And then you can use that exchange code to login with oauth:

let { data } = await this.client.http.sendPost(ENDPOINT.OAUTH_TOKEN, 'launcher', {
	grant_type: 'exchange_code',
	token_type: 'eg1',
	exchange_code: exchangeCode
});

After that, everything should work as expected.

```

Sorry for the lazy explanation, I'm currently busy with something else.

This will also require a few extra steps to get working for 2FA.

[This is the sample output from the showPleaseWait redirectUrl that you have to match for](https://gist.githubusercontent.com/Velkon/227cc76c55a77d6a45452bb0c7de8260/raw/bfb39d9c6deea010a30a5d529b4fccfe0e49c4c1/showPleaseWait)

(Look for `<CODE HERE>`) I guess you could run it as html/js but matching is probably easier

**Comment by ShadowRanger** [comment]
> @ShadowRanger This is how I'm doing it (Since Epic blocked the password token_type in OAuth, you now need to get an exchange_code)
> 
> ```
> Send a post request to https://accounts.launcher-website-prod07.ol.epicgames.com/login/doLauncherLogin with params:
> 
> fromForm: "yes",
> authType: null,
> linkExtAuth: null,
> client_id: clientId,
> redirectUrl: "https://accounts.launcher-website-prod07.ol.epicgames.com/login/showPleaseWait?client_id=" + clientId + "&rememberEmail=false",
> epic_username: email,
> password: password,
> rememberMe: "NO" // w/e you want between "NO" and "YES"
> 
> If login is ok it will return a JSON with redirectURL. (The same one you sent)
> 
> http Fetch the redirectURL:
> 
> Once the redirectURL is returned, 
> the only way I found to get the exchange_code is to string match for  
> com.epicgames.account.web.widgets.loginWithExchangeCode
> (Since it's a html page)
> 
> 
> And then you can use that exchange code to login with oauth:
> 
> let { data } = await this.client.http.sendPost(ENDPOINT.OAUTH_TOKEN, 'launcher', {
> 	grant_type: 'exchange_code',
> 	token_type: 'eg1',
> 	exchange_code: exchangeCode
> });
> 
> After that, everything should work as expected.
> ```
> Sorry for the lazy explanation, I'm currently busy with something else.
> 
> This will also require a few extra steps to get working for 2FA.
> 
> [This is the sample output from the showPleaseWait redirectUrl that you have to match for](https://gist.githubusercontent.com/Velkon/227cc76c55a77d6a45452bb0c7de8260/raw/bfb39d9c6deea010a30a5d529b4fccfe0e49c4c1/showPleaseWait)
> 
> (Look for `<CODE HERE>`) I guess you could run it as html/js but matching is probably easier

Well done on working that out. Thank you for sharing with us.

Quick question, what should the auth be for the header for the initial post request? Am currently failing to get a response making this post using the client_id from a client_credentials request and the launcher token.

**Comment by Velkon** [comment]
Oh yeah I forgot that part, lol.

You need to get a XSRF-TOKEN cookie from sending a `GET` request to `"https://accounts.launcher-website-prod07.ol.epicgames.com/login/doLauncherLogin?client_id=" + clientID + "&redirectUrl=https%3A%2F%2Faccounts.launcher-website-prod07.ol.epicgames.com%2Flogin%2FshowPleaseWait%3Fclient_id%3D" + clientID + "%26rememberEmail%3Dfalse"`
and the XSRF-TOKEN cookie should be in the response headers. (It has an empty body iirc)

I'm not really a web dev, so there might be a less hacky way of doing it. 

I did it all last night at 1 am and am too lazy to make it more proper since I'm only using it for some small personal stuff

Hope this helps

**Comment by Fyb3roptik** [comment]
Getting a 400 on the doLauncherLogin endpoint

**Comment by elayeek** [comment]
Here's my step-by-step, based on @Velkon (our lord and savior). It is a series of 3 http requests.


Request 1:
https://account-public-service-prod03.ol.epicgames.com/account/api/oauth/token
headers: {'Authorization': [BASIC EPIC TOKEN]}
body: {'grant_type': 'client_credentials', 'token_type': 'eg1'}

Take 'client_id' from response

Request 2:
https://accounts.launcher-website-prod07.ol.epicgames.com/login/doLauncherLogin?client_id=[CLIENT_ID]&redirectUrl=https%3A%2F%2Faccounts.launcher-website-prod07.ol.epicgames.com%2Flogin%2FshowPleaseWait%3Fclient_id%3D[CLIENT_ID]%26rememberEmail%3Dfalse

Take cookies from response


Request 3:
https://accounts.launcher-website-prod07.ol.epicgames.com/login/doLauncherLogin
cookies=[COOKIES FROM REQUEST 2 RESPONSE]
headers={'X-XSRF-TOKEN': ['XSRF-TOKEN' FROM REQUEST 2 RESPONSE COOKIES]}
body={
    'fromForm': "yes",
    'authType': '',
    'linkExtAuth': '',
                                  'client_id': [CLIENT_ID],
                                  'redirectUrl': "https://accounts.launcher-website-prod07.ol.epicgames.com/login/showPleaseWait?client_id=[CLIENT_ID]&rememberEmail=false",
                                  'epic_username': [YOUR USERNAME],
                                  'password': [YOUR PASSWORD],
                                  'rememberMe': "NO"
                              })`


From here continue with his instructions (fetch the redirectURL from the response and parse it), remember to also use the cookies to fetch the redirectURL (at least, that's what I did)

**Comment by ShadowRanger** [comment]
Although this new method of a fix may work fine, and be a potentially better option with support for 2FA and additional options,  an easier fix is to just update the launcher authorization key as displayed here: https://github.com/Tustin/fortnite-php/commit/58a1f7c94eb3c41c8bbb4b07abc4d744bbb5dce8

Credits to @Tustin for this fix.

**Comment by elayeek** [comment]
> 
> 
> Although this new method of a fix may work fine, and be a potentially better option with support for 2FA and additional options, an easier fix is to just update the launcher authorization key as displayed here: [Tustin/fortnite-php@58a1f7c](https://github.com/Tustin/fortnite-php/commit/58a1f7c94eb3c41c8bbb4b07abc4d744bbb5dce8)
> 
> Credits to @Tustin for this fix.

This method does seem better in my opinion since it seems easier to understand where it breaks of this repeats.

**Comment by SirWaddles** [comment]
Is there a way to get the updated launcher token, using the method above? Might be helpful to have a programmatic way of getting it, if it changes again.

**Comment by elayeek** [comment]
> 
> 
> Is there a way to get the updated launcher token, using the method above? Might be helpful to have a programmatic way of getting it, if it changes again.

I'm not sure that there is, we need to see how he got it. I keep getting the old one looking at fiddler.
While debugging this issue, we opened a discord for FN API devs to share knowledge instead of spamming these discussions (will compile a list of gits as well so ppl can find the apis):
https://discord.gg/pjy4cNJ

**Comment by SzymonLisowiec** [comment]
Changes has pushed. Great job guys! 🎉🎉🎉
