### ISSUE TITLE
Error while initialize or login p rocess.

### ISSUE THREAD

**Issue by R6z500** [SzymonLisowiec/node-epicgames-client#16]
hello I have this error on run my script : 
Error: TypeError: Cannot read property 'client_id' of null
    at AccountAuth.auth (/root/snipe_bot/node_modules/epicgames-client/src/Accou
nt/Auth.js:89:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18402) UnhandledPromiseRejectionWarning: Error while initialize or login p
rocess.

I have it since the update

**Comment by SzymonLisowiec** [comment]
Hello,
I suppose you don't use `await`. Can you show your code?

**Comment by R6z500** [comment]
Sorry, I managed to solve my problem with the update my code became obselete, I have a second problem, in the console of my bot, there is a smap of Communicator: Disconnected
Communicator: Trying reconnect ...

**Comment by SzymonLisowiec** [comment]
That isn't a problem. The bot sometimes losing connection with friends service and reconnecting.

**Comment by R6z500** [comment]
Yes, but it spammers it a lot of times in a very short time

**Comment by SzymonLisowiec** [comment]
I will check it.

**Comment by iXyles** [comment]
https://gyazo.com/dd8d86fdde7412684a2c795e131accb9 
Could this maybe help? Since I am having this issue after a few hours that I would need to "restart" the application to get it to work again.

**Comment by SzymonLisowiec** [comment]
Fixed in https://github.com/SzymonLisowiec/node-epicgames-client/commit/2b89b93d063c69c228e204959306b82b6d46081d

**Comment by WLTN1** [comment]
Hello, account, what i using for this using email verification, its here some solution, how login with email verification code? Some like i write email code to script? Thank you and have a nice day
