### ISSUE TITLE
Add methods and classes

### ISSUE THREAD

**Issue by mytopdog** [SzymonLisowiec/node-epicgames-client#17]
Seems alot easier to understand and easier to use if you could be able to do `message.reply()` or `invite.accept`

**Comment by ShadowRanger** [comment]
I personally think it is simple enough as it is, and that the code does not need to be over-complicated for something like this. That's just my opinion though.

**Comment by mytopdog** [comment]
I made a small version of this, and found that it's actually very nice to make it more object-oriented , I might release it if you'd like to have a look.

**Comment by SzymonLisowiec** [comment]
@mytopdog you can send pull-request, I will check it and maybe I merge to master. I was thinking about split a invites, users, messages and more on seperated objects. Unfortunately currently I don't need this in my project and I don't have free time for make it.

**Comment by ghost** [comment]
@mytopdog Are you planning to release it?

**Comment by mytopdog** [comment]
@xFirez sorry it seems I can't actually find it. I would definitely be happy to try again, i will when I get the time.

**Comment by SzymonLisowiec** [comment]
Today I've published v1.2.0 with some OOP. 🎉 Check REAMDE
