### ISSUE TITLE
updateStatus() does not set status

### ISSUE THREAD

**Issue by JaydenMaalouf** [SzymonLisowiec/node-epicgames-client#18]
Unfortunately, everytime I try use updateStatus() it fails. I have tried put strings, no strings, big strings etc. None have set my status correctly.

**Comment by SzymonLisowiec** [comment]
```javascript
const EGClient = require('node-epicgames-client').Client;

let eg = new EGClient({
 	email: 'EMAIL',
	password: 'PASSWORD',
	debug: console.log
});

eg.init().then(async (success) => {
	
	if(!success)
		throw new Error('Cannot initialize EpicGames launcher.');

	if(!await eg.login())
		throw new Error('Cannot login on EpicGames account.');
	
	eg.communicator.updateStatus('Hello World');
	
});
```
![image](https://user-images.githubusercontent.com/16546063/51059594-019cda80-15ed-11e9-90b6-b9fa6579f471.png)

**Comment by JaydenMaalouf** [comment]
Interesting. Is the current NPM version perhaps somehow out of date?
For some reason my intellisense isn't recognising communicator's functions. The updateStatus nor the sendMessage are picked up. Any suggestions? Am I missing an include?
(Also, it seems the NPM version is using the namespace "epicgames-client" whereas the Git version is "node-epicgames-client")

**Comment by JaydenMaalouf** [comment]
I just tried it again today and apparently it works? Not sure whats changed but thanks!
