### ISSUE TITLE
More extensive XMPP Features

### ISSUE THREAD

**Issue by battledash** [SzymonLisowiec/node-epicgames-client#19]
Just discovered this repo last night, I suspect this is how people like FNPL and FortniteTracker are making bot accounts. I used to be making a node.js program Konsole with Jaren until he got a c&d from Epic. We did pretty extensive xmpp stuff such as faking being in game, forcing people to ready up, infinite emotes, etc. Obviously forcing ready up won't work on a bot (theoretically) However I think some things like showing status as in the Epic launcher vs in Fortnite and being able to set if it's in game or not would be nice additions.

Here's what it looks like in the Launcher vs in Fortnite:
![image](https://user-images.githubusercontent.com/26150141/51569835-54c72680-1e52-11e9-8089-62c4e7f72fb4.png)

**Comment by BattleDashLeaks** [comment]
Not sure if this was the right place for a feature request, don't use GitHub a lot

**Comment by RobertoGraham** [comment]
@BattleDashLeaks sorry to deviate a bit but are you aware of how to retrieve a session (game/match) ID using an account ID?

**Comment by SzymonLisowiec** [comment]
@BattleDashLeaks Unfortunately I don't know, how to set "in game" status and etc. If you succeed, you can create pull request.

**Comment by battledash** [comment]
@SzymonLisowiec I'll probably do that if I get bored sometime.

@RobertoGraham It's impossible I'm pretty sure, It used to be possible to see a lot of stuff like that you could query an ID and then get literally everyone in the current match and game status and more however they patched a lot of those endpoints and now they just return nothing. The Endpoint was [https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/matchmaking/session/findPlayer/:id](https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/matchmaking/session/findPlayer/:id)

**Comment by SzymonLisowiec** [comment]
"In game" status has been implemented in [`node-epicgames-client@1.2.5`](https://github.com/SzymonLisowiec/node-epicgames-client) and [`node-epicgames-fortnite-client@1.2.2`](https://github.com/SzymonLisowiec/node-epicgames-fortnite-client). 🎉
