### ISSUE TITLE
Missing epicDomain

### ISSUE THREAD

**Issue by battledash** [SzymonLisowiec/node-epicgames-client#20]
Not a big issue but getEpicDomains returns  `[ 'unrealengine.com',
  'unrealtournament.com',
  'fortnite.com',
  'epicgames.com' ]`. There is also [epicgamesstore.com](https://epicgamesstore.com)

**Comment by SzymonLisowiec** [comment]
`getEpicDomains()` returns list from https://account-public-service-prod03.ol.epicgames.com/account/api/epicdomains/ssodomains. And from what I can see, *epicgamesstore.com* is only alias for *epicgames.com/store*
