### ISSUE TITLE
Status of a friend? (Offline/Online)

### ISSUE THREAD

**Issue by Hundeklemmen** [SzymonLisowiec/node-epicgames-client#3]
It would be awesome to add so we can see if a player is online or offline :) Maybe even game status

**Comment by SzymonLisowiec** [comment]
I'm afraid that's informations are accessible only for account's friends.

**Comment by SzymonLisowiec** [comment]
Added in version 1.0 (https://github.com/SzymonLisowiec/node-epicgames-client/commit/7bfb5410919035f915d17720c474de883b45fb3b)
