### ISSUE TITLE
Accept or deny friend requests

### ISSUE THREAD

**Issue by ShadowRanger** [SzymonLisowiec/node-epicgames-client#5]
Just a feature request which I noticed was not currently in. The ability to either accept or deny a received friend request such as through the friend:request event.

**Comment by SzymonLisowiec** [comment]
Just use `inviteFriend()` to accept friend request. In future I will add aliases `acceptFriendRequest` and `declineFriendRequest`.

**Comment by SzymonLisowiec** [comment]
Added in version `1.1.0`.
