### ISSUE TITLE
new message from ps4 logged in client not coming

### ISSUE THREAD

**Issue by adeelahmed1786** [SzymonLisowiec/node-epicgames-client#59]
i am able to receive/send message/DM/Whisper from everyone after accepting the friend requests, but when i send a friend request from ps4 and send message from Ps4 to nodejs client, client is unable to receive those messages. no event gotten in here 
```
launcher.communicator.on('friend:message', async(friendMessage) => {
console.log("msg coming from other people are fine, but i wouldnt run when ps4 guy messages me,i just dnt like him");
}
);
```

**Comment by SzymonLisowiec** [comment]
You should use `communicator` of specified game client, e.g. `epicgames-fortnite-client`.
```javascript
const Fortnite = require('epicgames-fortnite-client');
const app = await launcher.runGame(Fortnite);
app.communicator.on('friend:message', async(friendMessage) => {
  console.log(`${friendMessage.friend.id}: ${friendMessage.message}`);
});
```

**Comment by adeelahmed1786** [comment]
Thanks, 
i was using launcher's communicator,everyone please use above example to receive xmpp messages.
