### ISSUE TITLE
Add getFriendStatus Method

### ISSUE THREAD

**Issue by ShadowRanger** [SzymonLisowiec/node-epicgames-client#7]
A method to return the current status of a single friend would be very helpful, rather than having to listen to the friend:status event which only sends data when a friend's status changes. It would also be good if there could be another method to retrieve the status of multiple friends, similar to getProfiles

getFriendStatus(account_id) - Returns the status of a friend.
getFriendStatuses(account_ids) - Returns the status of multiple friends.

**Comment by SzymonLisowiec** [comment]
I will thinking about it, thanks for suggestion.

**Comment by SzymonLisowiec** [comment]
Added in `2.0.15`. Docs: https://epicgames-client.kysune.me/Client.html#getfriendstatus-id
