### ISSUE TITLE
Add ability to set current game

### ISSUE THREAD

**Issue by ShadowRanger** [SzymonLisowiec/node-epicgames-client#8]
The ability to set the game the account is currently on and will display through it's status would be a nice feature.

**Comment by SzymonLisowiec** [comment]
Implemented in [`node-epicgames-client@1.2.5`](https://github.com/SzymonLisowiec/node-epicgames-client) and [`node-epicgames-fortnite-client@1.2.2`](https://github.com/SzymonLisowiec/node-epicgames-fortnite-client). 🎉
