### ISSUE TITLE
"Directory's path to store" issue

### ISSUE THREAD

**Issue by Jbz797** [SzymonLisowiec/node-epicgames-client#86]
I want to install `node-epicgames-client`on Firebase functions.
The only folder with write permissions is the `tmp/` folder.

So I use this config : 
```javascript
  const launcher = new Launcher({
    email: 'E-MAIL',
    password: 'PASSWORD',
    store: '/tmp/.egstore',
  });
```

And i have this error : 
`Error: EROFS: read-only file system, mkdir '/workspace/.egstore'`

**Comment by SzymonLisowiec** [comment]
Documentation have wrong named parameter. Please replace `store` to `storage`.
