### ISSUE TITLE
eg.logout() doesn't work

### ISSUE THREAD

**Issue by R6z500** [SzymonLisowiec/node-epicgames-client#9]
Hello,
If I use eg.logout, I take error:
UnhandledPromiseRejectionWarning: errors.com.epicgames.common.oauth
.invalid_token
(node:17474) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 2)

**Comment by SzymonLisowiec** [comment]
Can you paste your code?

**Comment by R6z500** [comment]
Yes: https://pastebin.com/acWnPp8s

**Comment by SzymonLisowiec** [comment]
It looks like you aren't logged in EpicGames.

**Comment by R6z500** [comment]
If I am well connected, I connect to the launch of my bot discord

**Comment by SzymonLisowiec** [comment]
Are you sure, that error is caused by `eg.logout()`? Can you show error stack trace? Maybe you are logouted and trying do something?

**Comment by R6z500** [comment]
Yes I'm sure, but it's not a problem, in fact what I'm trying to do is that the account is continuously online, you can help me? Because after a while he breaks down

**Comment by SzymonLisowiec** [comment]
I need see full code where you used `node-epicgames-client`.

**Comment by ShadowRanger** [comment]
I can confirm experiencing the same issue where the client will randomly go offline for no reason. Here is how I initialize mine:
```
const EpicGamesClient = require('epicgames-client').Client;

const egClient = new EpicGamesClient({
	email: "hidden",
	password: "hidden"
});

try {
	await egClient.init();
	await egClient.login();
} catch (error) {
	console.log(error);
}
```
Is there a way I can enable debug mode or something to view debug logs?

**Comment by ShadowRanger** [comment]
After some testing I determined that the account logs out after around 10 minutes. It might be worth listening to the Stanza stream "disconnected" event and reconnecting when that happens.

**Comment by mytopdog** [comment]
https://github.com/legastero/stanza.io/blob/HEAD/docs/Reference.md#disconnected
Take a look at this?

**Comment by SzymonLisowiec** [comment]
While checking issue I found two problems:
- I forgot implement refreshing a token and account's session expired in ~8 hours.
- Sometimes EpicGames disconnecting XMPP client. Actually communicator will reconnecting, but in future I will check `enableKeepAlive` and `ping` methods.

Both problems has been fixed. Please do upgrade to `1.1.0`.

@ShadowRanger You can set constructor's option `debug` to e.g. `console.log`. More informations about constructor's options, here: https://github.com/SzymonLisowiec/node-epicgames-client#constructor-options

**Comment by mytopdog** [comment]
@SzymonLisowiec thanks.

**Comment by R6z500** [comment]
Okay verry thanks ! If I upgrade the version, the bot can stay online 24/24 ? Thanks again ^^

**Comment by SzymonLisowiec** [comment]
> Okay verry thanks ! If I upgrade the version, the bot can stay online 24/24 ? Thanks again ^^

Yes, your bot can working 24/7.
