### ISSUE TITLE
Be able to answer prompts in code instead of only stdin

### ISSUE THREAD

**Issue by Freezind** [SzymonLisowiec/node-epicgames-client#94]
Hi Kysune!

Thank you for this wonderful project!
I tried using it to claimer free games at epicgames automatically.
What made me really hard is [the code is fixed](https://github.com/SzymonLisowiec/node-epicgames-client/blob/master/src/Account/Auth.js#L8) to use stdin as input to answer prompts (e.g. 2-Factor Code). I can not do it while my server is deployed to the cloud. I hope there is a way to receive a variable as the answer.
Also, I hope the client is able to receive an argument to change the .esstore location.

Thanks again.

**Comment by SzymonLisowiec** [comment]
Hello,
Please check
https://epicgames-client.kysune.me/Client.html#login-options-exchangecode (you can pass `twoFactorCode` to `login()` method and `twoFactorCode` may be string or function which returns string)
and
https://epicgames-client.kysune.me/Client.html#store

**Comment by Freezind** [comment]
wow, I didn’t notice that, thanks for the quick reply
